application: perftracker
version: 3
runtime: python
api_version: 1
default_expiration: "1d"

builtins:
- datastore_admin: on

handlers:
- url: /
  static_files: templates/search.html
  upload: templates/search.html
- url: /do_(.*)
  static_files: templates/\1.html
  upload: templates/(.*).html
- url: /scripts
  static_dir: scripts
- url: /styles
  static_dir: styles
- url: /jst
  static_dir: jst
- url: /.*
  script: main.py
